/* Generated By:JavaCC: Do not edit this line. AnalizadorLUATokenManager.java */
package compiler;

import static compiler.AnalizadorLUA.lista;
import java.util.ArrayList;

/**
 * Token Manager.
 */
public class AnalizadorLUATokenManager implements AnalizadorLUAConstants {

    /**
     * Debug output.
     */
    public java.io.PrintStream debugStream = System.out;

    /**
     * Set debug output.
     */
    public void setDebugStream(java.io.PrintStream ds) {
        debugStream = ds;
    }

    private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1) {
        switch (pos) {
            case 0:
                if ((active0 & 0x800000L) != 0L) {
                    return 7;
                }
                if ((active0 & 0x7ffffeL) != 0L) {
                    jjmatchedKind = 60;
                    return 8;
                }
                return -1;
            case 1:
                if ((active0 & 0x8c08L) != 0L) {
                    return 8;
                }
                if ((active0 & 0x7f73f6L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 1;
                    return 8;
                }
                return -1;
            case 2:
                if ((active0 & 0x7f12b4L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 2;
                    return 8;
                }
                if ((active0 & 0x6142L) != 0L) {
                    return 8;
                }
                return -1;
            case 3:
                if ((active0 & 0x731284L) != 0L) {
                    if (jjmatchedPos != 3) {
                        jjmatchedKind = 60;
                        jjmatchedPos = 3;
                    }
                    return 8;
                }
                if ((active0 & 0xc0030L) != 0L) {
                    return 8;
                }
                return -1;
            case 4:
                if ((active0 & 0x30220L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 4;
                    return 8;
                }
                if ((active0 & 0x701084L) != 0L) {
                    return 8;
                }
                return -1;
            case 5:
                if ((active0 & 0x200L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 5;
                    return 8;
                }
                if ((active0 & 0x30020L) != 0L) {
                    return 8;
                }
                return -1;
            case 6:
                if ((active0 & 0x200L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 6;
                    return 8;
                }
                return -1;
            default:
                return -1;
        }
    }

    private final int jjStartNfa_0(int pos, long active0, long active1) {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
    }

    private int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 35:
                return jjStartNfaWithStates_0(0, 23, 7);
            case 37:
                jjmatchedKind = 29;
                return jjMoveStringLiteralDfa1_0(0x1000000000L);
            case 38:
                return jjMoveStringLiteralDfa1_0(0x100000000000L);
            case 40:
                return jjStopAtPos(0, 46);
            case 41:
                return jjStopAtPos(0, 47);
            case 42:
                jjmatchedKind = 27;
                return jjMoveStringLiteralDfa1_0(0x400000000L);
            case 43:
                jjmatchedKind = 25;
                return jjMoveStringLiteralDfa1_0(0x140000000L);
            case 44:
                return jjStopAtPos(0, 55);
            case 45:
                jjmatchedKind = 26;
                return jjMoveStringLiteralDfa1_0(0x280000000L);
            case 46:
                jjmatchedKind = 54;
                return jjMoveStringLiteralDfa1_0(0x200000000000L);
            case 47:
                jjmatchedKind = 28;
                return jjMoveStringLiteralDfa1_0(0x800000000L);
            case 58:
                return jjStopAtPos(0, 53);
            case 59:
                return jjStopAtPos(0, 52);
            case 60:
                jjmatchedKind = 40;
                return jjMoveStringLiteralDfa1_0(0x4000000000L);
            case 61:
                jjmatchedKind = 24;
                return jjMoveStringLiteralDfa1_0(0x2000000000L);
            case 62:
                jjmatchedKind = 41;
                return jjMoveStringLiteralDfa1_0(0x8000000000L);
            case 91:
                return jjStopAtPos(0, 50);
            case 93:
                return jjStopAtPos(0, 51);
            case 97:
                return jjMoveStringLiteralDfa1_0(0x2L);
            case 98:
                return jjMoveStringLiteralDfa1_0(0x4L);
            case 100:
                return jjMoveStringLiteralDfa1_0(0x8L);
            case 101:
                return jjMoveStringLiteralDfa1_0(0x70L);
            case 102:
                return jjMoveStringLiteralDfa1_0(0x380L);
            case 105:
                return jjMoveStringLiteralDfa1_0(0xc00L);
            case 108:
                return jjMoveStringLiteralDfa1_0(0x1000L);
            case 110:
                return jjMoveStringLiteralDfa1_0(0x6000L);
            case 111:
                return jjMoveStringLiteralDfa1_0(0x8000L);
            case 112:
                return jjMoveStringLiteralDfa1_0(0x400000L);
            case 114:
                return jjMoveStringLiteralDfa1_0(0x30000L);
            case 116:
                return jjMoveStringLiteralDfa1_0(0xc0000L);
            case 117:
                return jjMoveStringLiteralDfa1_0(0x100000L);
            case 119:
                return jjMoveStringLiteralDfa1_0(0x200000L);
            case 123:
                return jjStopAtPos(0, 48);
            case 124:
                return jjMoveStringLiteralDfa1_0(0x80000000000L);
            case 125:
                return jjStopAtPos(0, 49);
            case 126:
                return jjMoveStringLiteralDfa1_0(0x40000000000L);
            default:
                return jjMoveNfa_0(0, 0);
        }
    }

    private int jjMoveStringLiteralDfa1_0(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(0, active0, 0L);
            return 1;
        }
        switch (curChar) {
            case 38:
                if ((active0 & 0x100000000000L) != 0L) {
                    return jjStopAtPos(1, 44);
                }
                break;
            case 43:
                if ((active0 & 0x40000000L) != 0L) {
                    return jjStopAtPos(1, 30);
                }
                break;
            case 45:
                if ((active0 & 0x80000000L) != 0L) {
                    return jjStopAtPos(1, 31);
                }
                break;
            case 46:
                if ((active0 & 0x200000000000L) != 0L) {
                    return jjStopAtPos(1, 45);
                }
                break;
            case 61:
                if ((active0 & 0x100000000L) != 0L) {
                    return jjStopAtPos(1, 32);
                } else if ((active0 & 0x200000000L) != 0L) {
                    return jjStopAtPos(1, 33);
                } else if ((active0 & 0x400000000L) != 0L) {
                    return jjStopAtPos(1, 34);
                } else if ((active0 & 0x800000000L) != 0L) {
                    return jjStopAtPos(1, 35);
                } else if ((active0 & 0x1000000000L) != 0L) {
                    return jjStopAtPos(1, 36);
                } else if ((active0 & 0x2000000000L) != 0L) {
                    return jjStopAtPos(1, 37);
                } else if ((active0 & 0x4000000000L) != 0L) {
                    return jjStopAtPos(1, 38);
                } else if ((active0 & 0x8000000000L) != 0L) {
                    return jjStopAtPos(1, 39);
                } else if ((active0 & 0x40000000000L) != 0L) {
                    return jjStopAtPos(1, 42);
                }
                break;
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x80L);
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x30000L);
            case 102:
                if ((active0 & 0x400L) != 0L) {
                    return jjStartNfaWithStates_0(1, 10, 8);
                }
                break;
            case 104:
                return jjMoveStringLiteralDfa2_0(active0, 0x240000L);
            case 105:
                return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
            case 108:
                return jjMoveStringLiteralDfa2_0(active0, 0x30L);
            case 110:
                if ((active0 & 0x800L) != 0L) {
                    return jjStartNfaWithStates_0(1, 11, 8);
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x100042L);
            case 111:
                if ((active0 & 0x8L) != 0L) {
                    return jjStartNfaWithStates_0(1, 3, 8);
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x5100L);
            case 114:
                if ((active0 & 0x8000L) != 0L) {
                    return jjStartNfaWithStates_0(1, 15, 8);
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x480004L);
            case 117:
                return jjMoveStringLiteralDfa2_0(active0, 0x200L);
            case 124:
                if ((active0 & 0x80000000000L) != 0L) {
                    return jjStopAtPos(1, 43);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(0, active0, 0L);
    }

    private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(0, old0, 0L);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(1, active0, 0L);
            return 2;
        }
        switch (curChar) {
            case 99:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
            case 100:
                if ((active0 & 0x2L) != 0L) {
                    return jjStartNfaWithStates_0(2, 1, 8);
                } else if ((active0 & 0x40L) != 0L) {
                    return jjStartNfaWithStates_0(2, 6, 8);
                }
                break;
            case 101:
                return jjMoveStringLiteralDfa3_0(active0, 0x40004L);
            case 105:
                return jjMoveStringLiteralDfa3_0(active0, 0x600000L);
            case 108:
                if ((active0 & 0x2000L) != 0L) {
                    return jjStartNfaWithStates_0(2, 13, 8);
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x80L);
            case 110:
                return jjMoveStringLiteralDfa3_0(active0, 0x200L);
            case 112:
                return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
            case 114:
                if ((active0 & 0x100L) != 0L) {
                    return jjStartNfaWithStates_0(2, 8, 8);
                }
                break;
            case 115:
                return jjMoveStringLiteralDfa3_0(active0, 0x30L);
            case 116:
                if ((active0 & 0x4000L) != 0L) {
                    return jjStartNfaWithStates_0(2, 14, 8);
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x120000L);
            case 117:
                return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
            default:
                break;
        }
        return jjStartNfa_0(1, active0, 0L);
    }

    private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(1, old0, 0L);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(2, active0, 0L);
            return 3;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa4_0(active0, 0x1004L);
            case 99:
                return jjMoveStringLiteralDfa4_0(active0, 0x200L);
            case 101:
                if ((active0 & 0x10L) != 0L) {
                    jjmatchedKind = 4;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x80000L) != 0L) {
                    return jjStartNfaWithStates_0(3, 19, 8);
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x10020L);
            case 105:
                return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
            case 108:
                return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
            case 110:
                if ((active0 & 0x40000L) != 0L) {
                    return jjStartNfaWithStates_0(3, 18, 8);
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
            case 115:
                return jjMoveStringLiteralDfa4_0(active0, 0x80L);
            case 117:
                return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
            default:
                break;
        }
        return jjStartNfa_0(2, active0, 0L);
    }

    private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(2, old0, 0L);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(3, active0, 0L);
            return 4;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
            case 101:
                if ((active0 & 0x80L) != 0L) {
                    return jjStartNfaWithStates_0(4, 7, 8);
                } else if ((active0 & 0x200000L) != 0L) {
                    return jjStartNfaWithStates_0(4, 21, 8);
                }
                break;
            case 105:
                return jjMoveStringLiteralDfa5_0(active0, 0x20L);
            case 107:
                if ((active0 & 0x4L) != 0L) {
                    return jjStartNfaWithStates_0(4, 2, 8);
                }
                break;
            case 108:
                if ((active0 & 0x1000L) != 0L) {
                    return jjStartNfaWithStates_0(4, 12, 8);
                } else if ((active0 & 0x100000L) != 0L) {
                    return jjStartNfaWithStates_0(4, 20, 8);
                }
                break;
            case 114:
                return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
            case 116:
                if ((active0 & 0x400000L) != 0L) {
                    return jjStartNfaWithStates_0(4, 22, 8);
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x200L);
            default:
                break;
        }
        return jjStartNfa_0(3, active0, 0L);
    }

    private int jjMoveStringLiteralDfa5_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(3, old0, 0L);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(4, active0, 0L);
            return 5;
        }
        switch (curChar) {
            case 102:
                if ((active0 & 0x20L) != 0L) {
                    return jjStartNfaWithStates_0(5, 5, 8);
                }
                break;
            case 105:
                return jjMoveStringLiteralDfa6_0(active0, 0x200L);
            case 110:
                if ((active0 & 0x20000L) != 0L) {
                    return jjStartNfaWithStates_0(5, 17, 8);
                }
                break;
            case 116:
                if ((active0 & 0x10000L) != 0L) {
                    return jjStartNfaWithStates_0(5, 16, 8);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(4, active0, 0L);
    }

    private int jjMoveStringLiteralDfa6_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(4, old0, 0L);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(5, active0, 0L);
            return 6;
        }
        switch (curChar) {
            case 111:
                return jjMoveStringLiteralDfa7_0(active0, 0x200L);
            default:
                break;
        }
        return jjStartNfa_0(5, active0, 0L);
    }

    private int jjMoveStringLiteralDfa7_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(5, old0, 0L);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(6, active0, 0L);
            return 7;
        }
        switch (curChar) {
            case 110:
                if ((active0 & 0x200L) != 0L) {
                    return jjStartNfaWithStates_0(7, 9, 8);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(6, active0, 0L);
    }

    private int jjStartNfaWithStates_0(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }

    private int jjMoveNfa_0(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 14;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (;;) {
            if (++jjround == 0x7fffffff) {
                ReInitRounds();
            }
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 56) {
                                    kind = 56;
                                }
                                jjCheckNAddStates(0, 2);
                            } else if (curChar == 35) {
                                jjstateSet[jjnewStateCnt++] = 7;
                            } else if (curChar == 39) {
                                jjstateSet[jjnewStateCnt++] = 4;
                            } else if (curChar == 34) {
                                jjCheckNAdd(1);
                            }
                            break;
                        case 1:
                            if ((0xffffffff00000000L & l) != 0L) {
                                jjCheckNAddTwoStates(1, 2);
                            }
                            break;
                        case 2:
                            if (curChar == 34 && kind > 58) {
                                kind = 58;
                            }
                            break;
                        case 3:
                            if (curChar == 39) {
                                jjstateSet[jjnewStateCnt++] = 4;
                            }
                            break;
                        case 4:
                            if ((0x3ff000100000000L & l) != 0L) {
                                jjstateSet[jjnewStateCnt++] = 5;
                            }
                            break;
                        case 5:
                            if (curChar == 39 && kind > 59) {
                                kind = 59;
                            }
                            break;
                        case 6:
                            if (curChar == 35) {
                                jjstateSet[jjnewStateCnt++] = 7;
                            }
                            break;
                        case 8:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjstateSet[jjnewStateCnt++] = 8;
                            break;
                        case 9:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 56) {
                                kind = 56;
                            }
                            jjCheckNAddStates(0, 2);
                            break;
                        case 10:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 56) {
                                kind = 56;
                            }
                            jjCheckNAdd(10);
                            break;
                        case 11:
                            if ((0x3ff000000000000L & l) != 0L) {
                                jjCheckNAddTwoStates(11, 12);
                            }
                            break;
                        case 12:
                            if (curChar == 46) {
                                jjCheckNAdd(13);
                            }
                            break;
                        case 13:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 57) {
                                kind = 57;
                            }
                            jjCheckNAdd(13);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                        case 7:
                            if ((0x7fffffe07fffffeL & l) == 0L) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjCheckNAdd(8);
                            break;
                        case 1:
                            if ((0x7fffffe07fffffeL & l) != 0L) {
                                jjAddStates(3, 4);
                            }
                            break;
                        case 4:
                            if ((0x7fffffe07fffffeL & l) != 0L) {
                                jjstateSet[jjnewStateCnt++] = 5;
                            }
                            break;
                        case 8:
                            if ((0x7fffffe87fffffeL & l) == 0L) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjCheckNAdd(8);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt))) {
                return curPos;
            }
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }
    static final int[] jjnextStates = {
        10, 11, 12, 1, 2,};

    /**
     * Token literal values.
     */
    public static final String[] jjstrLiteralImages = {
        "", "\141\156\144", "\142\162\145\141\153", "\144\157", "\145\154\163\145",
        "\145\154\163\145\151\146", "\145\156\144", "\146\141\154\163\145", "\146\157\162",
        "\146\165\156\143\164\151\157\156", "\151\146", "\151\156", "\154\157\143\141\154", "\156\151\154",
        "\156\157\164", "\157\162", "\162\145\160\145\141\164", "\162\145\164\165\162\156",
        "\164\150\145\156", "\164\162\165\145", "\165\156\164\151\154", "\167\150\151\154\145",
        "\160\162\151\156\164", "\43", "\75", "\53", "\55", "\52", "\57", "\45", "\53\53", "\55\55", "\53\75",
        "\55\75", "\52\75", "\57\75", "\45\75", "\75\75", "\74\75", "\76\75", "\74", "\76",
        "\176\75", "\174\174", "\46\46", "\56\56", "\50", "\51", "\173", "\175", "\133", "\135",
        "\73", "\72", "\56", "\54", null, null, null, null, null, null, null, null, null,};

    /**
     * Lexer state names.
     */
    public static final String[] lexStateNames = {
        "DEFAULT",};
    static final long[] jjtoToken = {
        0x1fffffffffffffffL, 0x0L,};
    static final long[] jjtoSkip = {
        0xe000000000000000L, 0x1L,};
    protected SimpleCharStream input_stream;
    private final int[] jjrounds = new int[14];
    private final int[] jjstateSet = new int[28];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected char curChar;

    /**
     * Constructor.
     */
    public AnalizadorLUATokenManager(SimpleCharStream stream) {
        if (SimpleCharStream.staticFlag) {
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        }
        input_stream = stream;
    }

    /**
     * Constructor.
     */
    public AnalizadorLUATokenManager(SimpleCharStream stream, int lexState) {
        this(stream);
        SwitchTo(lexState);
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(SimpleCharStream stream) {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 14; i-- > 0;) {
            jjrounds[i] = 0x80000000;
        }
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(SimpleCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    /**
     * Switch to specified lex state.
     */
    public void SwitchTo(int lexState) {
        if (lexState >= 1 || lexState < 0) {
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
        } else {
            curLexState = lexState;
        }
    }

    protected Token jjFillToken() {
        final Token t;
        final String curTokenImage;
        final int beginLine;
        final int endLine;
        final int beginColumn;
        final int endColumn;
        String im = jjstrLiteralImages[jjmatchedKind];
        curTokenImage = (im == null) ? input_stream.GetImage() : im;
        beginLine = input_stream.getBeginLine();
        beginColumn = input_stream.getBeginColumn();
        endLine = input_stream.getEndLine();
        endColumn = input_stream.getEndColumn();
        t = Token.newToken(jjmatchedKind, curTokenImage);

        t.beginLine = beginLine;
        t.endLine = endLine;
        t.beginColumn = beginColumn;
        t.endColumn = endColumn;

        return t;
    }

    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    /**
     * Get the next Token.
     */
    public Token getNextToken() {
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (;;) {
            try {
                curChar = input_stream.BeginToken();
            } catch (java.io.IOException e) {
                jjmatchedKind = 0;
                matchedToken = jjFillToken();
                return matchedToken;
            }
            image = jjimage;
            image.setLength(0);
            jjimageLen = 0;

            try {
                input_stream.backup(0);
                while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L) {
                    curChar = input_stream.BeginToken();
                }
            } catch (java.io.IOException e1) {
                continue EOFLoop;
            }
            jjmatchedKind = 0x7fffffff;
            jjmatchedPos = 0;
            curPos = jjMoveStringLiteralDfa0_0();
            if (jjmatchedKind != 0x7fffffff) {
                if (jjmatchedPos + 1 < curPos) {
                    input_stream.backup(curPos - jjmatchedPos - 1);
                }
                if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                    matchedToken = jjFillToken();
                    TokenLexicalActions(matchedToken);
                    return matchedToken;
                } else {
                    continue EOFLoop;
                }
            }
            int error_line = input_stream.getEndLine();
            int error_column = input_stream.getEndColumn();
            String error_after = null;
            boolean EOFSeen = false;
            try {
                input_stream.readChar();
                input_stream.backup(1);
            } catch (java.io.IOException e1) {
                EOFSeen = true;
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
                if (curChar == '\n' || curChar == '\r') {
                    error_line++;
                    error_column = 0;
                } else {
                    error_column++;
                }
            }
            if (!EOFSeen) {
                input_stream.backup(1);
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
            }
            throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
        }
    }

    void TokenLexicalActions(Token matchedToken) {
        switch (jjmatchedKind) {
            case 1:
                image.append(jjstrLiteralImages[1]);
                lengthOfMatch = jjstrLiteralImages[1].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 2:
                image.append(jjstrLiteralImages[2]);
                lengthOfMatch = jjstrLiteralImages[2].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 3:
                image.append(jjstrLiteralImages[3]);
                lengthOfMatch = jjstrLiteralImages[3].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 4:
                image.append(jjstrLiteralImages[4]);
                lengthOfMatch = jjstrLiteralImages[4].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 5:
                image.append(jjstrLiteralImages[5]);
                lengthOfMatch = jjstrLiteralImages[5].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 6:
                image.append(jjstrLiteralImages[6]);
                lengthOfMatch = jjstrLiteralImages[6].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 7:
                image.append(jjstrLiteralImages[7]);
                lengthOfMatch = jjstrLiteralImages[7].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 8:
                image.append(jjstrLiteralImages[8]);
                lengthOfMatch = jjstrLiteralImages[8].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 9:
                image.append(jjstrLiteralImages[9]);
                lengthOfMatch = jjstrLiteralImages[9].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 10:
                image.append(jjstrLiteralImages[10]);
                lengthOfMatch = jjstrLiteralImages[10].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 11:
                image.append(jjstrLiteralImages[11]);
                lengthOfMatch = jjstrLiteralImages[11].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 12:
                image.append(jjstrLiteralImages[12]);
                lengthOfMatch = jjstrLiteralImages[12].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 13:
                image.append(jjstrLiteralImages[13]);
                lengthOfMatch = jjstrLiteralImages[13].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 14:
                image.append(jjstrLiteralImages[14]);
                lengthOfMatch = jjstrLiteralImages[14].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 15:
                image.append(jjstrLiteralImages[15]);
                lengthOfMatch = jjstrLiteralImages[15].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 16:
                image.append(jjstrLiteralImages[16]);
                lengthOfMatch = jjstrLiteralImages[16].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 17:
                image.append(jjstrLiteralImages[17]);
                lengthOfMatch = jjstrLiteralImages[17].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 18:
                image.append(jjstrLiteralImages[18]);
                lengthOfMatch = jjstrLiteralImages[18].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 19:
                image.append(jjstrLiteralImages[19]);
                lengthOfMatch = jjstrLiteralImages[19].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 20:
                image.append(jjstrLiteralImages[20]);
                lengthOfMatch = jjstrLiteralImages[20].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 21:
                image.append(jjstrLiteralImages[21]);
                lengthOfMatch = jjstrLiteralImages[21].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 22:
                image.append(jjstrLiteralImages[22]);
                lengthOfMatch = jjstrLiteralImages[22].length();
                System.out.println("Palabra reservada --> " + image);
                lista.add("Palabra reservada --> " + image);
                break;
            case 23:
                image.append(jjstrLiteralImages[23]);
                lengthOfMatch = jjstrLiteralImages[23].length();
                System.out.println("Simbolo reservado --> " + image);
                lista.add("Simbolo reservado --> " + image);
                break;
            case 24:
                image.append(jjstrLiteralImages[24]);
                lengthOfMatch = jjstrLiteralImages[24].length();
                System.out.println("Asignacion --> " + image);
                lista.add("Asignacion --> " + image);
                break;
            case 25:
                image.append(jjstrLiteralImages[25]);
                lengthOfMatch = jjstrLiteralImages[25].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 26:
                image.append(jjstrLiteralImages[26]);
                lengthOfMatch = jjstrLiteralImages[26].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 27:
                image.append(jjstrLiteralImages[27]);
                lengthOfMatch = jjstrLiteralImages[27].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 28:
                image.append(jjstrLiteralImages[28]);
                lengthOfMatch = jjstrLiteralImages[28].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 29:
                image.append(jjstrLiteralImages[29]);
                lengthOfMatch = jjstrLiteralImages[29].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 30:
                image.append(jjstrLiteralImages[30]);
                lengthOfMatch = jjstrLiteralImages[30].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 31:
                image.append(jjstrLiteralImages[31]);
                lengthOfMatch = jjstrLiteralImages[31].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 32:
                image.append(jjstrLiteralImages[32]);
                lengthOfMatch = jjstrLiteralImages[32].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 33:
                image.append(jjstrLiteralImages[33]);
                lengthOfMatch = jjstrLiteralImages[33].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 34:
                image.append(jjstrLiteralImages[34]);
                lengthOfMatch = jjstrLiteralImages[34].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 35:
                image.append(jjstrLiteralImages[35]);
                lengthOfMatch = jjstrLiteralImages[35].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 36:
                image.append(jjstrLiteralImages[36]);
                lengthOfMatch = jjstrLiteralImages[36].length();
                System.out.println("Operador Aritmetico --> " + image);
                lista.add("Operador Aritmetico --> " + image);
                break;
            case 37:
                image.append(jjstrLiteralImages[37]);
                lengthOfMatch = jjstrLiteralImages[37].length();
                System.out.println("Operador para comparacion --> " + image);
                lista.add("Operador para comparacion --> " + image);
                break;
            case 38:
                image.append(jjstrLiteralImages[38]);
                lengthOfMatch = jjstrLiteralImages[38].length();
                System.out.println("Operador para comparacion --> " + image);
                lista.add("Operador para comparacion --> " + image);
                break;
            case 39:
                image.append(jjstrLiteralImages[39]);
                lengthOfMatch = jjstrLiteralImages[39].length();
                System.out.println("Operador para comparacion --> " + image);
                lista.add("Operador para comparacion --> " + image);
                break;
            case 40:
                image.append(jjstrLiteralImages[40]);
                lengthOfMatch = jjstrLiteralImages[40].length();
                System.out.println("Operador para comparacion --> " + image);
                lista.add("Operador para comparacion --> " + image);
                break;
            case 41:
                image.append(jjstrLiteralImages[41]);
                lengthOfMatch = jjstrLiteralImages[41].length();
                System.out.println("Operador para comparacion --> " + image);
                lista.add("Operador para comparacion --> " + image);
                break;
            case 42:
                image.append(jjstrLiteralImages[42]);
                lengthOfMatch = jjstrLiteralImages[42].length();
                System.out.println("Operador para comparacion --> " + image);
                lista.add("Operador para comparacion --> " + image);
                break;
            case 43:
                image.append(jjstrLiteralImages[43]);
                lengthOfMatch = jjstrLiteralImages[43].length();
                System.out.println("Operador logico --> " + image);
                lista.add("Operador logico --> " + image);
                break;
            case 44:
                image.append(jjstrLiteralImages[44]);
                lengthOfMatch = jjstrLiteralImages[44].length();
                System.out.println("Operador logico --> " + image);
                lista.add("Operador logico --> " + image);
                break;
            case 45:
                image.append(jjstrLiteralImages[45]);
                lengthOfMatch = jjstrLiteralImages[45].length();
                System.out.println("Concatenador de Strings --> " + image);
                lista.add("Concatenador de Strings --> " + image);
                break;
            case 46:
                image.append(jjstrLiteralImages[46]);
                lengthOfMatch = jjstrLiteralImages[46].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 47:
                image.append(jjstrLiteralImages[47]);
                lengthOfMatch = jjstrLiteralImages[47].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 48:
                image.append(jjstrLiteralImages[48]);
                lengthOfMatch = jjstrLiteralImages[48].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 49:
                image.append(jjstrLiteralImages[49]);
                lengthOfMatch = jjstrLiteralImages[49].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 50:
                image.append(jjstrLiteralImages[50]);
                lengthOfMatch = jjstrLiteralImages[50].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 51:
                image.append(jjstrLiteralImages[51]);
                lengthOfMatch = jjstrLiteralImages[51].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 52:
                image.append(jjstrLiteralImages[52]);
                lengthOfMatch = jjstrLiteralImages[52].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 53:
                image.append(jjstrLiteralImages[53]);
                lengthOfMatch = jjstrLiteralImages[53].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 54:
                image.append(jjstrLiteralImages[54]);
                lengthOfMatch = jjstrLiteralImages[54].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 55:
                image.append(jjstrLiteralImages[55]);
                lengthOfMatch = jjstrLiteralImages[55].length();
                System.out.println("Puntuacion --> " + image);
                lista.add("Puntuacion --> " + image);
                break;
            case 56:
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Valor --> " + image);
                lista.add("Valor --> " + image);
                break;
            case 57:
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Valor --> " + image);
                lista.add("Valor --> " + image);
                break;
            case 58:
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Valor --> " + image);
                lista.add("Valor --> " + image);
                break;
            case 59:
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Valor --> " + image);
                lista.add("Valor --> " + image);
                break;
            case 60:
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Identificador --> " + image);
                lista.add("Identificador --> " + image);
                break;
            default:
                break;
        }
    }

    private void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        } while (start++ != end);
    }

    private void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        } while (start++ != end);
    }

}
